spring:
  application:
    name: config-client
  cloud:
    config:
      label: main
      profile: dev
  config:
    import: optional:configserver:http://localhost:8888

management:
  endpoint:
    shutdown:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"

data:
  env: NaN
  user:
    username: NaN
    password: NaN

