server:
  port: 8888

spring:
  application:
    name: config-single-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/darta0809/spring-cloud-demo.git
          username:
          password:
          default-label: main
          search-paths: spring-cloud-config-repo
          clone-on-start: true
        bootstrap: true
      enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: 123123

# Spring cloud bus 發送配置
management:
  endpoint:
    refresh:
      enabled: true
    shutdown:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"